@startuml Diagramas

title Diagrama de Secuencia - Juego de Plataformas 2D

actor Jugador
participant "Juego" as Juego
participant "Personaje Principal" as Personaje
participant "Enemigo" as Enemigo
participant "Bloque" as Bloque
participant "Poder" as Poder
participant "Config" as Config
participant "Interfaz Gráfica" as Interfaz
participant "Main" as Main


Jugador -> Juego: Inicia el juego
activate Juego

Juego -> Personaje: Carga al personaje
activate Personaje

Jugador -> Personaje: Controla el personaje (saltar, mover)
Jugador -> Juego: Interactúa con el juego

Juego -> Enemigo: Genera enemigos
activate Enemigo
Juego -> Bloque: Coloca Bloques
activate Bloque
Juego -> Poder: Coloca objetos para recoger
activate Poder

Personaje -> Enemigo: Interactúa con enemigos
Personaje -> Bloque: Colisiona con Bloques
Personaje -> Poder: Recoge poder

Juego -> Interfaz: Actualiza la interfaz gráfica
activate Interfaz
Interfaz --> Jugador: Muestra la puntuación y el estado del juego

Config -> Interfaz: Setea la ventana donde se crea el mapa

Juego -> Main: ejecuta el programa
activate Main


deactivate Juego
deactivate Personaje
deactivate Enemigo
deactivate Bloque
deactivate Poder
deactivate Interfaz
deactivate Main
@enduml
